### ISSUE TITLE
RuntimeError: hook 'backward_hook_norm' has returned an incorrect number of values (got 1, but expected 3)

### ISSUE THREAD

**Issue by xyzacademic** [csdongxian/skip-connections-matter#3]
Hello, Dongxian. Hope everything is going well.

Your paper is quite interesting.

I ran it for ResNet 18 and 50 but it gave me an error every time. 

I don't know if it is because of Pytorch version (1.7 in my python environment) or not. The error happens in line "inputs_adv = adversary.perturb(inputs, pred.detach().view(-1))."

def backward_hook_norm(module, grad_in, grad_out):
    # normalize the gradient to avoid gradient explosion or vanish
    std = torch.std(grad_in[0])
    return (grad_in[0] / std,)

If I remove the line that runs hook for BatchNorm, everything is fine. But I don't know if it will affect the attack performance a lot. Looks like transferability is not good currently after I remove it.

Please tell me if you have any idea how to fix it.

Thank you.

**Comment by csdongxian** [comment]
Hello, I have released more codes and upload the dataset used in our paper.

We add the backward_hook_norm, since SGM always degrades the gradients, which may result in gradient vanish when gamma is extremely small (e.g. gamma=0.01).  For the best gamma 0.2 for ResNet, you can just remove these lines without performance degradation. For the performance degradation you met,  is the gamma set to 0.2 for ResNet on ImageNet?

Besides, this hook is for the whole  BasicBlock or Bottleneck , not for BatchNorm.  In my previous implementation, it uses the length of module name to register, which may meet problems when the model is slightly changed (e.g. using torch.nn.DataParalell).

Please let me know if there are any problem. Good luck :)

**Comment by xyzacademic** [comment]
I did experiments for CIFAR10 only, with modifying the kernel size and stride in the first layer of ResNet50 and 18 from torchvision. Gamma is 0.5.
Could you give me some arguments setting for CIFAR10? I knew ResNet18 and 50's structure is different.

**Comment by xyzacademic** [comment]
Thank you.
The code works very well. I did experiments on getting adversaries from ResNet18/ResNet50 to attack VGG19_BN. VGG's accuracy drops from 93% to 18%/26% correspondingly.
Parameters are 0.2/0.4 for ResNet18/50. Epsilon=8. Step_size=2, 10 iters for PGD.

I post the pre-trained model repository link here for helping other users reproducing results easier.
https://github.com/huyvnphan/PyTorch_CIFAR10

**Comment by machengcheng2016** [comment]
@xyzacademic It is because the backward hook on common layers such as Conv2d and Linear will lead to three grads, while hook on activation layer like ReLU will lead to only one grad. I think the author confuses such difference here.
To remedy this, you should `return (grad_in[0] / std, grad_in[1] / std, grad_in[2] / std)`. Please give it a try :sweat_smile:
